/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liz_cmdtool_CmdIf */

#ifndef _Included_com_liz_cmdtool_CmdIf
#define _Included_com_liz_cmdtool_CmdIf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liz_cmdtool_CmdIf
 * Method:    runCmd
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liz_cmdtool_CmdIf_runCmd
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
